### ISSUE TITLE
NPM link on 'work' page should link to npmjs.org/~jlord

### ISSUE THREAD

**Issue by joshhartigan** [jlord/old-site#13]
hi!
  currently your link on the /work page, that is supposed to go to your npm profile:
![screen shot 2014-12-07 at 12 44 00](https://cloud.githubusercontent.com/assets/5961708/5331047/4eca5b86-7e0f-11e4-976d-15cb0d4ea168.png)

  is going to https://npmjs.org/jlord (404), so it should go to https://npmjs.org/~jlord (with a tilde).
  sorry to be fussy, but it should help out :smile:

**edit**: the reason this is an issue and not a PR is because I'm not sure about how your build system for the website works. sorry!

**Comment by jlord** [comment]
Ah, whoops! Thanks so much for catching this! :sparkles:
