### ISSUE TITLE
twittter instead of twitter

### ISSUE THREAD

**Issue by vnodecg** [jlord/old-site#4]
Hey JLord was visiting your site.
Found a typo in href i.e., twittter instead of twitter :smile: 

[Search results](https://github.com/jlord/jlord.github.io/search?q=twittter&type=Code)

**Comment by jlord** [comment]
Eek, thanks! Sorry took so long to get to this, I forgot to turn 'watching' on on my own repo :blush:

**Comment by vnodecg** [comment]
He he :smile:
