### ISSUE TITLE
broken link to 'your own instagram' on http://jlord.github.io/instagram.html

### ISSUE THREAD

**Issue by brianzelip** [jlord/old-site#7]
not sure why cause the source file here in GH links to the hard URL for the post, but on the web the link is relative to ur local environment (http://localhost:5567/blog/your-own-instagram.html).

am enjoying reading through ur work. Im bent towards civic engagement, teaching, and (learning) node.js too!

**Comment by brianzelip** [comment]
also, ur gh-pages instance of this no longer has 16 but 18 instagrammies

(ie "These are the last 16 pictures in my...")

**Comment by jlord** [comment]
Ah! Thanks!! 

Also, I've updated the layout so now it's actually 20 instagrammies! :camera:
